export const games = [
  {
    id: 1,
    title: 'CyberWorld 2077',
    description: 'Кіберпанк світ з відкритими можливостями.',
    genre: 'RPG, Екшен, Відкритий світ',
    image: '/images/game1.jpg',
    trailer: 'https://www.w3schools.com/html/mov_bbb.mp4',
    price: 699,
    discount: 30,
    platforms: ['windows', 'linux', 'mac'],
    rating: 4,
    reviews: [
      '“Гра супер! Атмосфера просто 🔥 — Ігор”',
      '“Дуже деталізований світ, цікаві квести — Марина”',
    ],
    requirements: {
      os: 'Windows 10',
      cpu: 'Intel i5 / Ryzen 5',
      gpu: 'GTX 1060 / RX 580',
      ram: '8 GB',
      disk: '70 GB',
    },
  },
  {
    id: 2,
    title: 'Fantasy Realms',
    description: 'Магічний світ, де ти герой давнього пророцтва.',
    genre: 'RPG, Пригоди',
    image: '/images/game2.jpg',
    trailer: 'https://www.w3schools.com/html/movie.mp4',
    price: 499,
    discount: 20,
    platforms: ['windows'],
    rating: 5,
    reviews: [
      '“Епічна історія! Грав без перерви 3 дні — Андрій”',
      '“Захоплюючий геймплей і музика — Олена”',
    ],
    requirements: {
      os: 'Windows 10',
      cpu: 'Intel i7',
      gpu: 'RTX 2060',
      ram: '16 GB',
      disk: '55 GB',
    },
  },
  {
    id: 3,
    title: 'Speed Racers X',
    description: 'Адреналінові перегони у футуристичних містах.',
    genre: 'Гонки, Аркада',
    image: '/images/game3.jpg',
    trailer: 'https://www.w3schools.com/html/mov_bbb.mp4',
    price: 299,
    discount: 0,
    platforms: ['windows', 'mac'],
    rating: 3,
    reviews: [
      '“Швидко, драйвово, яскраво — Максим”',
      '“Нагадує класичні гонки, але з новим стилем — Саша”',
    ],
    requirements: {
      os: 'Windows 8 / 10',
      cpu: 'Intel i3',
      gpu: 'GTX 750',
      ram: '4 GB',
      disk: '12 GB',
    },
  },
  {
    id: 4,
    title: 'Zombie Survival',
    description: 'Боротьба за виживання у світі після зомбі-апокаліпсису.',
    genre: 'Шутер, Виживання',
    image: '/images/game4.jpg',
    trailer: 'https://www.w3schools.com/html/movie.mp4',
    price: 399,
    discount: 50,
    platforms: ['windows'],
    rating: 4,
    reviews: [
      '“Напружено до останнього патрона! — Ілля”',
      '“Гра тримає у напрузі, особливо вночі — Юлія”',
    ],
    requirements: {
      os: 'Windows 10',
      cpu: 'Intel i5',
      gpu: 'GTX 1050',
      ram: '8 GB',
      disk: '40 GB',
    },
  },
  {
    id: 5,
    title: 'Pixel Puzzle World',
    description: 'Кольорові головоломки з чарівною атмосферою.',
    genre: 'Платформер, Пазли, Інді',
    image: '/images/game5.jpg',
    trailer: 'https://www.w3schools.com/html/mov_bbb.mp4',
    price: 149,
    discount: 10,
    platforms: ['windows', 'linux'],
    rating: 4,
    reviews: [
      '“Ідеальна гра для вечора — Настя”',
      '“Маленька, але дуже затягуюча! — Петро”',
    ],
    requirements: {
      os: 'Windows 7+',
      cpu: 'Будь-який',
      gpu: 'Інтегрована',
      ram: '2 GB',
      disk: '500 MB',
    },
  },
  {
    id: 6,
    title: 'Battle Command: Arena',
    description: 'Тактична онлайн-стратегія з масштабними битвами.',
    genre: 'Стратегія, Онлайн',
    image: '/images/game6.jpg',
    trailer: 'https://www.w3schools.com/html/movie.mp4',
    price: 0,
    discount: 0,
    platforms: ['windows', 'mac'],
    rating: 5,
    reviews: [
      '“Безкоштовно і змагально! — Богдан”',
      '“Тактична глибина і баланс — супер! — Ірина”',
    ],
    requirements: {
      os: 'Windows 10',
      cpu: 'Intel i5',
      gpu: 'GTX 750',
      ram: '6 GB',
      disk: '8 GB',
    },
  },
  {
    id: 7,
    title: 'Space Colonies',
    description: 'Побудуй свою колонію на далеких планетах!',
    genre: 'Стратегія, Симулятор, Sci-Fi',
    image: '/images/game7.jpg',
    trailer: 'https://www.w3schools.com/html/mov_bbb.mp4',
    price: 459,
    discount: 15,
    platforms: ['windows', 'mac'],
    rating: 4,
    reviews: [
      '“Космічні пригоди й будівництво — вау! — Андрій”',
      '“Підсадилася на годину, а пройшло три — Оля”',
    ],
    requirements: {
      os: 'Windows 10',
      cpu: 'Intel i5',
      gpu: 'GTX 960',
      ram: '8 GB',
      disk: '25 GB',
    },
  },
  {
    id: 8,
    title: 'Haunted Mansion',
    description: 'Зловісний детектив у проклятому будинку.',
    genre: 'Горор, Квест, Атмосфера',
    image: '/images/game8.jpg',
    trailer: 'https://www.w3schools.com/html/movie.mp4',
    price: 279,
    discount: 0,
    platforms: ['windows'],
    rating: 4,
    reviews: [
      '“Темрява й головоломки — жахливо круто! — Дмитро”',
      '“Люблю таке, 10/10 — Аліна”',
    ],
    requirements: {
      os: 'Windows 8/10',
      cpu: 'Intel i3',
      gpu: 'GTX 660',
      ram: '4 GB',
      disk: '18 GB',
    },
  },
  {
    id: 9,
    title: 'SkyFlight VR',
    description: 'Поринь у небо в режимі віртуальної реальності.',
    genre: 'VR, Літалки, Симулятор',
    image: '/images/game9.jpg',
    trailer: 'https://www.w3schools.com/html/mov_bbb.mp4',
    price: 899,
    discount: 40,
    platforms: ['windows'],
    rating: 5,
    reviews: [
      '“Це як справжній політ — Євген”',
      '“Один з найкращих VR-досвідів — Валерія”',
    ],
    requirements: {
      os: 'Windows 10',
      cpu: 'Intel i7',
      gpu: 'RTX 2070',
      ram: '16 GB',
      disk: '30 GB',
    },
  },
  {
    id: 10,
    title: 'BattleChess 3000',
    description: 'Футуристичні шахи з анімацією бою.',
    genre: 'Настільна, Стратегія',
    image: '/images/game10.jpg',
    trailer: 'https://www.w3schools.com/html/movie.mp4',
    price: 199,
    discount: 0,
    platforms: ['windows', 'linux'],
    rating: 4,
    reviews: [
      '“Шахи, які я ще не бачив — Роман”',
      '“Гарна графіка і штучний інтелект — Олексій”',
    ],
    requirements: {
      os: 'Windows 7+',
      cpu: 'Intel i3',
      gpu: 'GT 1030',
      ram: '4 GB',
      disk: '3 GB',
    },
  },
  {
    id: 11,
    title: 'Deep Ocean Explorer',
    description: 'Пірнай у глибини океану та досліджуй незвідане.',
    genre: 'Симулятор, Пригоди',
    image: '/images/game11.jpg',
    trailer: 'https://www.w3schools.com/html/mov_bbb.mp4',
    price: 349,
    discount: 10,
    platforms: ['windows', 'mac'],
    rating: 3,
    reviews: [
      '“Класна графіка і розслаблюючий настрій — Артем”',
    ],
    requirements: {
      os: 'Windows 10',
      cpu: 'Intel i5',
      gpu: 'GTX 1050 Ti',
      ram: '8 GB',
      disk: '15 GB',
    },
  },
  {
    id: 12,
    title: 'Samurai Duel',
    description: 'Бійцівська арена в стилі феодальної Японії.',
    genre: 'Файтинг, Екшен',
    image: '/images/game12.jpg',
    trailer: 'https://www.w3schools.com/html/movie.mp4',
    price: 329,
    discount: 25,
    platforms: ['windows'],
    rating: 4,
    reviews: [
      '“Фехтування відчувається дуже круто — Микита”',
    ],
    requirements: {
      os: 'Windows 10',
      cpu: 'Intel i5',
      gpu: 'GTX 1050',
      ram: '6 GB',
      disk: '12 GB',
    },
  },
  {
    id: 13,
    title: 'Castle Builder',
    description: 'Будуй замки, укріплення й розвивай королівство.',
    genre: 'Симулятор, Стратегія',
    image: '/images/game13.jpg',
    trailer: 'https://www.w3schools.com/html/mov_bbb.mp4',
    price: 229,
    discount: 0,
    platforms: ['windows', 'mac', 'linux'],
    rating: 4,
    reviews: [
      '“Гарна економіка і дизайн — Іван”',
    ],
    requirements: {
      os: 'Windows 8+',
      cpu: 'Intel i3',
      gpu: 'GTX 750',
      ram: '4 GB',
      disk: '10 GB',
    },
  },
  {
    id: 14,
    title: 'Alien Invasion Defense',
    description: 'Захистіть Землю від хвиль прибульців.',
    genre: 'Tower Defense, Sci-Fi',
    image: '/images/game14.jpg',
    trailer: 'https://www.w3schools.com/html/movie.mp4',
    price: 129,
    discount: 0,
    platforms: ['windows'],
    rating: 3,
    reviews: [
      '“Класика жанру, дуже затягує — Катерина”',
    ],
    requirements: {
      os: 'Windows 7+',
      cpu: 'Intel Pentium',
      gpu: 'Інтегрована',
      ram: '2 GB',
      disk: '500 MB',
    },
  },
  {
    id: 15,
    title: 'Music Runner',
    description: 'Біжи в ритмі музики, уникаючи перешкод.',
    genre: 'Ритм, Аркада',
    image: '/images/game15.jpg',
    trailer: 'https://www.w3schools.com/html/mov_bbb.mp4',
    price: 89,
    discount: 0,
    platforms: ['windows', 'linux'],
    rating: 4,
    reviews: [
      '“Музика + рух = кайф — Софія”',
    ],
    requirements: {
      os: 'Windows 7+',
      cpu: 'Intel Celeron',
      gpu: 'Інтегрована',
      ram: '2 GB',
      disk: '1 GB',
    },
  },
  {
    id: 16,
    title: 'Kingdom War Simulator',
    description: 'Побудуй армію та знищ ворогів у масових битвах.',
    genre: 'Симулятор, Стратегія',
    image: '/images/game16.jpg',
    trailer: 'https://www.w3schools.com/html/movie.mp4',
    price: 259,
    discount: 20,
    platforms: ['windows'],
    rating: 5,
    reviews: [
      '“Битви епічні, як у кіно — Сергій”',
    ],
    requirements: {
      os: 'Windows 10',
      cpu: 'Intel i5',
      gpu: 'GTX 960',
      ram: '8 GB',
      disk: '25 GB',
    },
  },
];